### ISSUE TITLE
Consider optimizing API provider calls

### ISSUE THREAD

**Issue by Siegrift** [api3dao/signed-api#110]
https://github.com/api3dao/signed-api/issues/50#issuecomment-1798095742

**Comment by Siegrift** [comment]
Currently, we use Airnode feeds in away that there a particular endpoint is present in two Signed API triggers (one for API3 and one for Nodary).

So all in all this optimization can reduce the API provider calls by 50%, which is significant.

**Comment by bbenligiray** [comment]
I'm not sure if I've understood. Are we calling the API twice, once for the API3 signed API and once for the Nodary signed API?

**Comment by Siegrift** [comment]
Yes. Each trigger is [handled independently](https://github.com/api3dao/signed-api/blob/74340efc3dcbf61da2dd91e4293289b91c195608/packages/airnode-feed/src/fetch-beacon-data.ts#L15).
