### ISSUE TITLE
Migrate nodary pool API to signed API instance

### ISSUE THREAD

**Issue by Siegrift** [api3dao/signed-api#111]
Blocked by https://github.com/api3dao/signed-api/issues/84 and https://github.com/api3dao/signed-api/issues/139

See: https://api3workspace.slack.com/archives/C05S589E7B4/p1699373345734739?thread_ts=1699370419.254739&cid=C05S589E7B4

**Comment by bbenligiray** [comment]
https://github.com/api3dao/tasks/issues/507 is closed now, so there is a production signed API deployment. The only thing that needs to be done here is to take down https://pool.nodary.io/. However, https://example.api3dev.com/ depends on that and we don't want to waste time on updating that. So I'd consider this blocked until we launch OEV.

**Comment by bbenligiray** [comment]
https://pool.nodary.io/ no longer works. DNS record is to be removed.
