### ISSUE TITLE
Archive the Nodary versions of the repo

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/signed-api#13]
Nodary has a signed API and pusher implementation. The respective repos should be archived to avoid confusion once Nodary switches to using this implementation.

**Comment by bbenligiray** [comment]
Will be done after the Nodary deployment is wound down

**Comment by Siegrift** [comment]
The nodary deployment migration is tracked in https://github.com/api3dao/signed-api/issues/111

**Comment by Siegrift** [comment]
The [original Nodary repo](https://github.com/nodaryio/signed-api) is archived.
