### ISSUE TITLE
Remove signed data validation

### ISSUE THREAD

**Issue by Siegrift** [api3dao/signed-api#161]
See the second point of https://api3workspace.slack.com/archives/C05S589E7B4/p1701957615232169?thread_ts=1701869036.467659&cid=C05S589E7B4

This relates to https://github.com/api3dao/signed-api/issues/22 but is only concerned about the POST requests made from Airnode feed to the Signed API. These requests are currently computationally heavy beacuse of signed data signature verification. This should be changed so that the full request body is signed and we only need to do a single verification check.

**Comment by bbenligiray** [comment]
One option is to omit [the Airnode address](https://github.com/api3dao/signed-api/blob/main/packages/api/src/schema.ts#L49) from the POST schema and use the address implied by the signature. This is probably not a good idea in case we want to update the authentication method later.

As a separate note, will you yeet the entire validation, e.g. checking if Beacon ID matches the Airnode address and the template ID?

**Comment by Siegrift** [comment]
> One option is to omit [the Airnode address](https://github.com/api3dao/signed-api/blob/main/packages/api/src/schema.ts#L49) from the POST schema and use the address implied by the signature. This is probably not a good idea in case we want to update the authentication method later.

That way we would need to verify the signature and pay the performance penalty. But yeah, we may not need the Airnode address if we can know it from auth (e.g. have auth tokens per Airnode feed). I don't think changing is an issue, because if auth is changed, we need to update both API and Airnode feed anyway.

As a separate note, will you yeet the entire validation, e.g. checking if Beacon ID matches the Airnode address and the template ID?

Yes, I was planning to remove both as both require computing a hash which I believe is the bottleneck.

**Comment by Siegrift** [comment]
I've changed the issue title and plan to fix it with https://github.com/api3dao/signed-api/pull/159

**Comment by Siegrift** [comment]
Agreed on call and [followup discussion](https://api3workspace.slack.com/archives/C05S589E7B4/p1702465837876959?thread_ts=1702378878.241199&cid=C05S589E7B4) NOT to remove the signed data verification. Instead we will deploy a Signed API per Airnode feed which reduces the load of Signed API significantly.
