### ISSUE TITLE
Add airnode address to `POST /` endpoint

### ISSUE THREAD

**Issue by bdrhn9** [api3dao/signed-api#185]
When we try to scale signed-api over airnode addresses on a single domain, it's possible to route `GET /delayed/<airnodeAddress>` and `GET /real-time/<airnodeAddress>` because the airnode address uniquely determines which container to use. However, routing the `POST /` address that accepts signed data complicates the routing process in a simple way. So adding airnode address to POST endpoint e.g. `POST /<airnodeAddress>` will make routing easier. 

Blocker for https://github.com/api3dao/tasks/issues/507

**Comment by bbenligiray** [comment]
Also remove `GET /`?

**Comment by bdrhn9** [comment]
> Also remove `GET /`?

I created separate [issue](https://github.com/api3dao/signed-api/issues/188). It's not blocking https://github.com/api3dao/tasks/issues/507.
