### ISSUE TITLE
Remove `GET /` endpoint

### ISSUE THREAD

**Issue by bdrhn9** [api3dao/signed-api#188]
Similar to https://github.com/api3dao/signed-api/issues/185, this endpoint prevents the scaling signed-api over airnode addresses on a single domain (if this endpoint is going to be utilized). Additionally the endpoint isn't leveraged anywhere so it looks that it's redundant. So we can remove it.

It's not blocker for https://github.com/api3dao/tasks/issues/507, because Nodary just won't serve this endpoint.

**Comment by Siegrift** [comment]
When implementing this, be sure to check if the AWS is fine with this. Currently the GET / serves as a healthcheck endpoint. Maybe that on it's own is a valid reason to keep this.

**Comment by Siegrift** [comment]
Based on my [quick read](https://stackoverflow.com/questions/23921370/aws-load-balancer-with-no-health-check-or-make-it-work-with-non-200-response) there needs to be some "healthcheck" endpoint for AWS ELB. Preserving the "GET /" as health-check seems like a good idea to me even if there was a way to use AWS ELB.

> It's not blocker for https://github.com/api3dao/tasks/issues/507, because Nodary just won't serve this endpoint.

This is the same for API3 deployments and I can't imagine situation where having the "GET /" would be problematic.
