### ISSUE TITLE
Fatal error in Airnode feed

### ISSUE THREAD

**Issue by metobom** [api3dao/signed-api#207]
Nodary Airnode feed process failed with [this](https://api3.grafana.net/explore?schemaVersion=1&panes=%7B%22spw%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bairnode%3D%5C%220xc52EeA00154B4fF1EbbF8Ba39FDe37F1AC3B9Fd4%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221706648610000%22,%22to%22:%221706654190000%22%7D%7D%7D&orgId=1) error and because we read config from raw Github URL and change the deployment file's location (from `candidate-deployments` to the `active-deployments`) after the deployment, CF tried to redeploy the app but wget kept throwing 404 error.

> CF tried to redeploy the app but wget kept throwing 404 error.

As a solution to this, I will update CF EntryPoint in a way to try `candidate-deployments` path first if fails try [active-deployments](https://raw.githubusercontent.com/api3dao/api-integrations/main/data/apis/nodary/deployments/active-deployments/api3-20240123-airnode-feed.json). 

@Siegrift for visibility.

**Comment by Siegrift** [comment]
The error message doesn't tell much :/ 

I couldn't find related issues for `Check failed: is_clonable_js_type || is_clonable_wasm_type.`. Do we have access to the Nodary Airnode feed to check some metrics? Maybe it was some CPU/memory spike or memory leak.

In regards to Github URLs we need to [make sure that the production ones are immutable](https://api3workspace.slack.com/archives/C05S589E7B4/p1700910873307079?thread_ts=1700498242.003409&cid=C05S589E7B4).

**Comment by metobom** [comment]
> Do we have access to the Nodary Airnode feed to check some metrics?

Unfortunately, we don't have any metrics.

**Comment by bdrhn9** [comment]
>  Do we have access to the Nodary Airnode feed to check some metrics?

For debugging purpose, I activated `ECS CloudWatch Container Insights` to collect metrics from the containers. If we experience the issue again, it will be helpful. 

It's charged extra so generally it wouldn't be enabled. But it's easy to enable it in CF template:

```diff
"AppCluster": {
      "Type": "AWS::ECS::Cluster",
      "Properties": {
        "ClusterName": "AirnodeFeedCluster-<SOME_ID>",
+       "ClusterSettings": [
+         {
+           "Name": "containerInsights",
+           "Value": "enabled"
+         }
+       ]
      }
    }
```

**Comment by Siegrift** [comment]
We should be able to see at least CPU and memory usage, but when I was stress testing the container it was able to handle the load so I'd be surprised if it was caused by this. Hopefully, we will be able to reproduce it again with more insights.

**Comment by metobom** [comment]
The same error occurred in TwelveData's deployment too.

**Comment by Siegrift** [comment]
Thanks, for reference [this is the error in Grafana](https://api3.grafana.net/explore?schemaVersion=1&panes=%7B%22cot%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22airnode-feed%5C%22,%20airnode%3D%5C%220x31C7db0e12e002E071ca0FF243ec4788a8AD189F%5C%22%7D%20%7C%3D%20%60%60%20%21%3D%20%60%5C%22debug%5C%22%60%20%21%3D%20%60Pushed%20signed%20data%20updates%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221706824140000%22,%22to%22:%221706827860000%22%7D%7D%7D&orgId=1).

The service seems operational again after AWS restart, so I suspect there is some memory leak. I will try to reproduce it and fix it.

**Comment by Siegrift** [comment]
Btw. it seems that the message in Grafana is trimmed out. E.g. the error message pasted [in this issue](https://github.com/lovell/sharp/issues/2205) contains more information and suggests race condition inside Node.js.

**Comment by bdrhn9** [comment]
I was mistaken, the metrics are still in place. Here is a snapshot of them. I expected to see a gradual increase in memory usage, but it seems that's not the case.

![Screenshot from 2024-02-02 14-55-16](https://github.com/api3dao/signed-api/assets/29605305/3b99c63f-4260-4913-bfac-228d8183f25c)

**Comment by Siegrift** [comment]
Happened again with Finnage.

**Comment by Siegrift** [comment]
I created an issue on Node.js repo https://github.com/nodejs/node/issues/51652 and hope someone responds. An idea would be to try migrating to a different Node.js image (or version).

**Comment by metobom** [comment]
It happend to coinpaprika too. One possibly useful information is, it happens with the Airnode feeds that include more data feeds.

**Comment by metobom** [comment]
Happened in dxFeed too, which has 113 data feeds.

**Comment by bbenligiray** [comment]
I wonder if this will happen with a configuration that excludes the Grafana log shipping stuff

**Comment by aquarat** [comment]
> An idea would be to try migrating to a different Node.js image (or version). Especially, there are some mentions to [use the Slim package instead of Alpine](https://stackoverflow.com/a/71423030).

A good idea. AFAIK they use different C libraries 👌  This definitely looks like a runtime issue.

**Comment by aquarat** [comment]
I'm currently trying to recreate this issue by simulating lots of feeds.

**Comment by aquarat** [comment]
Can anyone confirm the architecture? arm64 right?

**Comment by aquarat** [comment]
I've been running it locally (docker images built from `main` on amd64, both intervals set to 0) with 15 000 feeds and so far it's been fine. I had to increase the memory (tentatively gave it 2048m). I'll let it run for a few hours and see what happens.

**Comment by aquarat** [comment]
So it's been running locally now with 15 000 feeds for about 4 hours and it hasn't died - so it may be something specific to AWS or the RAM allocation (which affects processor resources). I'll try with reduced RAM.

**Comment by aquarat** [comment]
It ran overnight with 15000 feeds and a reduced-speed CPU to try and simulate resource constraints. It still didn't crash, so I'm thinking this may be specific to AWS.

**Comment by aquarat** [comment]
It's been running for three days, 15k feeds, some fuzzing and it's still running, no crashes, so... this is a hard bug to trace 😆

**Comment by metobom** [comment]
It happened again in TwelveData's Airnode feed.

**Comment by aquarat** [comment]
My local instance eventually crashed because it ran out of log space (400 GBs) - so I haven't been able to recreate this locally. Upgrading to Node 20 may help.

**Comment by Siegrift** [comment]
Let's close this one, otherwise it's going to remain on the board forever. After crashing, the service restarts so we are not affected much by this as of now.

We've tried using a different Node image (didn't help) and upgraded Node version (not confirmed whether it helps).

**Comment by aquarat** [comment]
Has this happened again with the update Node version? Just curious.

**Comment by bbenligiray** [comment]
I think it did

**Comment by metobom** [comment]
API providers' current deployments are `0.5.1` and Node 20 is used in `0.6.0`.
