### ISSUE TITLE
Investigate possible log reduction in Signed API and Airnode feed

### ISSUE THREAD

**Issue by Siegrift** [api3dao/signed-api#208]
Relates to https://github.com/api3dao/tasks/issues/695

We've noticed that we are sending too much logs which is costly. The Signed APIs have been redeployed with level INFO to reduce the costs, but pretty much all of the INFO logs [come from the server](https://github.com/api3dao/signed-api/blob/9aa11fa654b67d9ec6a5731e03c80a54e1138c9b/packages/signed-api/src/server.ts#L21) when the request is received (which is arguably still too often for INFO level). Better information would be to:
* log some stats periodically (e.g. how many requests have been received throughout some period).
* log out debug level information (request body, headers) when there is some validation error.

Similar analysis can be done for Airnode feed, which should be even more reasonable with log usage because its deployed by API providers.

**Comment by bbenligiray** [comment]
I agree that individual "request sent"/"request received" INFO logs are redundant (so these may be downgraded to DEBUG)

**Comment by Siegrift** [comment]
I mentioned on a call, that there is some advantage of these, for example to verify caching. That said, it would be possible even if we log a stats message.

**Comment by Siegrift** [comment]
> > I agree that individual "request sent"/"request received" INFO logs are redundant (so these may be downgraded to DEBUG)

> I mentioned on a call, that there is some advantage of these, for example to verify caching. That said, it would be possible even if we log a stats message.

I also used these logs heavily for https://github.com/api3dao/signed-api/issues/211#issuecomment-1924619661 to debug the Signed API 502 response. After doing that, I think these logs are important.

After redeploying the Signed APIs with INFO level, they [produce only ~2 GB per 24 hours](https://api3.grafana.net/a/grafana-logvolumeexplorer-app/log-volume-explorer?expr=app%3D%22signed-api%22&rangeRaw=%7B%22from%22%3A%22now-24h%22%2C%22to%22%3A%22now%22%7D&range=%7B%22from%22%3A%222024-02-01T19%3A58%3A31.722Z%22%2C%22to%22%3A%222024-02-02T19%3A58%3A31.722Z%22%7D&ds=grafanacloud-logs) which has negligible costs per month (30$). As a note, the "Received request ..." is the [only log message from Signed API](https://api3.grafana.net/explore?schemaVersion=1&panes=%7B%221py%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22signed-api%5C%22%7D%20%21%3D%20%60Received%20request%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:5000,%22legendFormat%22:%22%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1).

I did a [similar drill down for Airnode feeds](https://api3.grafana.net/explore?schemaVersion=1&panes=%7B%221py%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22airnode-feed%5C%22%7D%20%7C%3D%20%60%5C%22level%5C%22:%5C%22warn%5C%22%60%20or%20%60%5C%22level%5C%22:%5C%22info%5C%22%60%20or%20%60%5C%22level%5C%22:%5C%22error%5C%22%60%20%21%3D%20%60Pushed%20signed%60%20%21%3D%20%60Failed%20to%20post%20process%60%20%21%3D%20%60configHash%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:5000,%22legendFormat%22:%22%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1) and for INFO level there are these logs:
- [Heartbeat log](https://github.com/api3dao/signed-api/blob/f6e03d45932c979520a4d6c257933b15dffbd7b9/packages/airnode-feed/src/heartbeat/heartbeat.ts#L46) - Which is logged independently of the log level we use (can't be disabled).
- [Pushed signed data to Signed API](https://github.com/api3dao/signed-api/blob/f6e03d45932c979520a4d6c257933b15dffbd7b9/packages/airnode-feed/src/api-requests/signed-api.ts#L79)
- Warnings and errors - E.g. post-processing failures, API provider and Signed API errors.

Based on the above, we can expect similar logging costs to the Signed APIs. So I'd keep this as is.

**Comment by Siegrift** [comment]
Agreed to keep things as is. In the future we may log much more because of https://github.com/api3dao/signed-api/issues/222
