### ISSUE TITLE
Allow API to serve delayed data

### ISSUE THREAD

**Issue by Siegrift** [api3dao/signed-api#21]
See: https://api3workspace.slack.com/archives/C05S589E7B4/p1695136091683809

What this means is that the API should be (statically = at startup time) configurable to serve multiple versions of data. API will need to keep older signed data. However, it should automatically prune data that is not needed.

This entails:
- [x] Modify API configuration to allow serving multiple data types (delayed, non-delayed).
- [x] Remove upserting HTTP endpoint
- [x] Keep all beacon signed data to allow serving the data point
- [x] Document the configuration and how to serve multiple data types.

**Comment by bbenligiray** [comment]
To be specific, if a 15 seconds delay is enforced and the signed API has 14 and 16 seconds-old data, it returns the 16 seconds-old data.
