### ISSUE TITLE
Implement API authentication

### ISSUE THREAD

**Issue by Siegrift** [api3dao/signed-api#22]
See: https://api3workspace.slack.com/archives/C05S589E7B4/p1695139756669989?thread_ts=1695136091.683809&cid=C05S589E7B4

At least the non-delayed data should be hidden behind auth.

**Comment by bbenligiray** [comment]
In the self-hosted setup the API provider may want to use their own authentication scheme, which is why I said this feels out of scope similar to caching

**Comment by Siegrift** [comment]
Based on [this](https://api3workspace.slack.com/archives/C05S589E7B4/p1701869036467659) discussion, we want to use the API authentication to avoid the need to verify signed data, which turns out to be a big bottlenect.

**Comment by Siegrift** [comment]
The outcome was to have the signed API POST request bodies to be signed. The signer has to be in [the whitelist](https://github.com/api3dao/signed-api/issues/98) and the match Airnode addresses in the body.
