### ISSUE TITLE
Log received data in INFO level

### ISSUE THREAD

**Issue by Siegrift** [api3dao/signed-api#222]
The pricing collector currently needs to call the API3 Signed APIs for data frequently and process the data in memory to create aggregated pricing value. This is a service that needs to be run and managed. An alternative solution would be to store the data in logs and have a simpler lambda that queries these logs and computes the value retrospectively.

**Comment by bbenligiray** [comment]
Flag in config?

**Comment by Siegrift** [comment]
> Flag in config?

I'm not sure what you mean.

**Comment by bdrhn9** [comment]
Like following:
```json
{
  "endpoints": [
    {
      "urlPath": "/real-time",
      "authTokens": ["${REAL_TIME_ENDPOINT_AUTH_TOKEN}"],
      "delaySeconds": 0
    },
    {
      "urlPath": "/delayed",
      "authTokens": null,
      "delaySeconds": 15
    }
  ],
  "allowedAirnodes": [
    { "address": "0xbF3137b0a7574563a23a8fC8badC6537F98197CC", "authTokens": ["${AIRNODE_FEED_AUTH_TOKEN}"] }
  ],
  "stage": "local",
  "version": "0.5.0",
  "logHeartbeat": false,
  "logApiData": true,
}

```

But as I see, all logging behavior is being configured in [.env.example](https://github.com/api3dao/signed-api/blob/eb6ab2047a14d38045a9da8e807d1f2cbfc34fff/packages/signed-api/.env.example). Maybe for this implementation, it is better to define environment variable like LOG_HEARTBEAT=<true/false>, LOG_APIDATA=<true/false>.

I'd prefer to have them in environment variable instead config. WDYT?

**Comment by Siegrift** [comment]
I am not a fan of having this configurable. If this is a must, I agree with:
> it is better to define environment variable like LOG_HEARTBEAT=<true/false>, LOG_APIDATA=<true/false>

**Comment by Siegrift** [comment]
What do you mean by "function of the deployment"? However, I recognize that the inability to disable the heartbeat at the moment is somewhat inconvenient.

I still don't get why we need `LOG_APIDATA` configurable.
