### ISSUE TITLE
Timestamps are not signed with post processed data

### ISSUE THREAD

**Issue by Ashar2shahid** [api3dao/signed-api#228]
One of the reasons for moving from preprocessingV1 to V2 was to be able to modify the responses. Currently Airnode Feed doesn't mimic airnode behavior seen here: https://github.com/api3dao/airnode/blob/ea29aefb12e75d919ebf4bca1e53673baa72c4d5/packages/airnode-node/src/api/index.ts#L277

**Comment by aquarat** [comment]
> @aquarat @v_ponline can you take a look?

I'll take a look at this now 👌
