### ISSUE TITLE
Import unsafe processing instead of copy pasting it

### ISSUE THREAD

**Issue by Siegrift** [api3dao/signed-api#23]
See: https://api3workspace.slack.com/archives/C05S589E7B4/p1695199725392089?thread_ts=1695139260.280159&cid=C05S589E7B4

**Comment by BTT21000** [comment]
This issue should be migrated to the api3dao/commons repo

**Comment by bbenligiray** [comment]
We need to create an issue "Export unsafe processing" at the commons repo but this issue should remain because commons exporting it is one thing and this repo importing it is another

**Comment by Siegrift** [comment]
Duplicate of https://github.com/api3dao/signed-api/issues/77
