### ISSUE TITLE
Secrets interpolation doesn't match airnode interpolation

### ISSUE THREAD

**Issue by Ashar2shahid** [api3dao/signed-api#234]
currently secret interpolation does basic replacement but would break in [pre/post processing snippets](https://docs.api3.org/reference/ois/latest/processing.html#interpolation). Suggested fix is to follow the same regex used here: https://github.com/api3dao/airnode/blob/ea29aefb12e75d919ebf4bca1e53673baa72c4d5/packages/airnode-validator/src/api/api.ts#L70 and copy the [method](https://github.com/api3dao/airnode/blob/ea29aefb12e75d919ebf4bca1e53673baa72c4d5/packages/airnode-validator/src/api/api.ts#L72)

**Comment by andreogle** [comment]
We probably want this to be in `@api3/commons`?

**Comment by Siegrift** [comment]
Mhh, I am sure I copied the function from some other repo. I am surprised it is different and definitely should be fixed.

> We probably want this to be in @api3/commons?

Yes, [there is already and issue for that](https://github.com/api3dao/commons/issues/43).
