### ISSUE TITLE
Finalize repo QA compliance

### ISSUE THREAD

**Issue by BTT21000** [api3dao/signed-api#264]
As part of the TM issue https://github.com/api3dao/tasks/issues/849 for QA, some requirements need to be addressed:

### Repo setup requirements as per [new_repo_creation_checklist.md](https://github.com/api3dao/tasks/blob/main/Technical%20management/Tasks%20documentation/new_repo_creation_checklist.md):
- [x] Link to some relevant page if applicable (e.g. api3 docs, npm package link, ...)

### Package setup requirements as per [new_package_creation_checklist.md](https://github.com/api3dao/tasks/blob/main/Technical%20management/Tasks%20documentation/new_package_creation_checklist.md):
- [x] Edit the `README.md` as needed so that it looks well presented on www.npmjs.com, and provides a clear and comprehensive description about the package, including installation instructions, usage examples, and any other relevant information. Package update changesets should not be included in the `README.md`.
- [x] Add relevant `package.json` fields as applicable (e.g. such that repo links and keywords show up in NPM, compare [this](https://www.npmjs.com/package/@material/button) to [this](https://www.npmjs.com/package/@api3/ois))

**Comment by Siegrift** [comment]
> Note: This only applies if the dapi-management package is maintained

Why? The checklist items make sense to me even though this repo does is not related to dapi-management.
