### ISSUE TITLE
Improve Signed API and airnode-feed monitoring

### ISSUE THREAD

**Issue by PrenaamD** [api3dao/signed-api#270]
1. Setup additional alerts for Signed API and airnode-feed
2. To monitor errors in the Signed API and airnode-feed Grafana logs, directives should be given related to what to specifically look for in the logs to avoid being overwhelmed by airnode-feed API call errors when investigating an issue.
3. The monitoring guidelines might need to be updated to include the new directives once defined.

**Comment by Siegrift** [comment]
Alerts are sent to https://api3workspace.slack.com/archives/C06QTTM722H and https://api3workspace.slack.com/archives/C06RKPATH6U

Tasks documentation has been updated, with the exception on **WHO** is responsible for these and how the on-call works for these. Burak had a good point about this on todays call, that this should be formalized. For now I am going to handle all of them across all channels.
