### ISSUE TITLE
Auto-stagger signed API updates to throttle API calls optimally

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/signed-api#50]
The pusher needs to call an API to get data, potentially once for every template for which signed data is being pushed. In the event that these calls are done concurrently, it's possible for the API to rate-limit or drop these. Currently, we have a rate limiting functionality in the pusher config to limit the number of such concurrent calls. This is not ideal because this is one more parameter to tune per API, and works by holding off on sending API calls.

Ideally, the pusher would automatically stagger its signed API updates over time, which means it would automatically rate limit in an optimal manner without necessarily holding back on sending any API calls as it does with rate limiting. The current config schema doesn't allow this. Consider the following config
```
"triggers": {
    "signedApiUpdates": [
      {
        "signedApiName": "localhost",
        "templateIds": [
          "0xcc35bd1800c06c12856a87311dd95bfcbb3add875844021d59a929d79f3c99bd"
        ],
        "fetchInterval": 5,
        "updateDelay": 0
      },
      {
        "signedApiName": "localhost",
        "templateIds": [
          "0x086130c54864b2129f8ac6d8d7ab819fa8181bbe676e35047b1bca4c31d51c66"
        ],
        "fetchInterval": 15,
        "updateDelay": 0
      },
      {
        "signedApiName": "localhost",
        "templateIds": [
          "0x1d65c1f1e127a41cebd2339f823d0290322c63f3044380cbac105db8e522ebb9"
        ],
        "fetchInterval": 15,
        "updateDelay": 0
      }
    ]
  }
```
Each item in `triggers.signedApiUpdates` requires an API call, and it's not obvious how one would auto-stagger three API calls of which one needs to happen every 5 seconds and two needs to happen every 15 seconds.

A simple yet non-complete solution would be to (remove rate limiting and) fuzz `fetchInterval` every time it is used so that concurrent API calls is a rare and unfortunate coincidence that we don't need to worry about.

**Comment by Siegrift** [comment]
> A simple yet non-complete solution would be to (remove rate limiting and) fuzz fetchInterval every time it is used so that concurrent API calls is a rare and unfortunate coincidence that we don't need to worry about.

Yeah. I like that. I propose every to schedule the loop every `fetchInterval + Math.random() * fetchInterval / 10` (add at maximum 10% delay).

**Comment by Siegrift** [comment]
A larger change would be to split the "data fetching" and "pushing" phase into two. This would be beneficial because data would need to be fetched only with one configuration (with the maximum frequency necessary). We would still do the pre/post processing trick to save RPC calls but there could be multiple "pushing" configurations created (e.g. with different delays) for the same template.

**Comment by bbenligiray** [comment]
My main goal with the unified "Call API to get the data, push it to the signed API" flow was to avoid the slack caused by two separate loops. We want to do <=1 second lag (not for Airseeker but for the pull oracle use case). When you have two loops with a fetch interval of 1 second and update interval of 1 second, the mean lag will be 1.5 seconds, which is a big hit.
This is not easily doable in Airseeker which needs to support multiple providers/chains (and we don't care about the additional lag all that much), so that has two loops.

**Comment by Siegrift** [comment]
Yeah, the two loops will suffer this problem if they are disjoint. A possibility would be to have a "middle ground" where we would fetch endpoint data with maximum frequency, but trigger the updates directly (we can easily check if a particular `signedApiUpdates` wants to push the data).

That said, this is out of scope of that issue. The benefit is more optimized data provider calls, which might be worth it but I think we should continue discussion in a separate issue.

**Comment by Siegrift** [comment]
Created https://github.com/api3dao/signed-api/issues/110 because this issue will be closed by the respective (linked) PR.
