### ISSUE TITLE
Have a way for the signed API identify the pusher deployment

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/signed-api#66]
A heartbeat is critical for verifying that an API provider has deployed and if their deployment is live. We use a heartbeat for this purpose in Airnode.

We can depend on the data pushes as a sort of a heartbeat. However, the deployment still needs to be identified. We need a pusher config field, which gets signed and pushed along with the signed data for this purpose. This should work in a similar way to the Airnode heartbeat in that the signature should have a timestamp and the receiver should expect it to be fresh (to prevent deployment identifier signatures from being replayed).

**Comment by bbenligiray** [comment]
Discussed on the October 3 call to just log the config file hash and have the partner API ship the logs to us

**Comment by metobom** [comment]
Should we close this issue? 

See: https://github.com/api3dao/signed-api/issues/96

**Comment by Siegrift** [comment]
Yeah. Thanks for noticing.
