### ISSUE TITLE
Publish a release candidate Docker container 

### ISSUE THREAD

**Issue by metobom** [api3dao/signed-api#74]

**Comment by Siegrift** [comment]
@bbenligiray You can publish. I wanted to double check the images locally, but I remember that they are checked on CI in this flow https://github.com/api3dao/signed-api/blob/4138fa9977009a899fe1a42af5ad41983d13704a/.github/workflows/main.yml#L65

**Comment by bbenligiray** [comment]
@metobom Published [`api3/pusher:0.1.0-rc1`](https://hub.docker.com/r/api3/pusher/tags)

I didn't publish the API container image because [I wasn't sure what to name it](https://api3workspace.slack.com/archives/C05S589E7B4/p1696929697273889) and we don't need it atm anyway

**Comment by bbenligiray** [comment]
I'm not documenting anything because this is not a proper release
