### ISSUE TITLE
Create instructions how to deploy signed API on cloud

### ISSUE THREAD

**Issue by Siegrift** [api3dao/signed-api#84]
Blocked by https://github.com/api3dao/signed-api/issues/9

We want to have the API deployable to cloud. The deployment would ideally be based on how we deploy pusher.

**Comment by bbenligiray** [comment]
We'll finalize the pusher template and then hopefully this will be just a few additions on top of that

**Comment by Siegrift** [comment]
Added milestone, becuase this issue blocks the performance test (which also has this milestone).
