### ISSUE TITLE
Create instructions to deploy pusher on cloud provider

### ISSUE THREAD

**Issue by Siegrift** [api3dao/signed-api#9]
We have docker images for signed API and pusher. We need the pusher to be deployeable conveniently for the user.

I wanted to deploy it to AWS without TF, thinking it would be easy, but after watching https://www.youtube.com/watch?v=YDNSItBN15w I stand corrected. It would be better to have terraform script that automates this.

**Comment by Siegrift** [comment]
Burak mentioned on call cloud formation, which might be simpler. It's also OK to be opinionated and go for AWS primarily.

**Comment by bbenligiray** [comment]
It would be x2 nice if we could embed the config/secrets in the cloud formation file so that we have the API provider deploy with a single file

**Comment by bbenligiray** [comment]
Blocked by https://github.com/api3dao/signed-api/issues/41

**Comment by Siegrift** [comment]
For production use the FE, for testing and development use the Docker instance. In case you need to deploy on AWS in the sort term, follow @metobom [guide ](https://github.com/api3dao/signed-api/issues/41#issuecomment-1762742570).
