### ISSUE TITLE
Add logs to use as heartbeat

### ISSUE THREAD

**Issue by metobom** [api3dao/signed-api#96]
Pusher needs to log the below with a minute frequency: 

```
pusherConfigHash = hash(config) // config is not interpolated
heartbeatSignature = sign(
  hash(
    airnodeAddress,
    stage, 
    pusherVersion,
    currentTimestamp,
    deploymentTimestamp,
    pusherConfigHash
  )
) // deploymentTimestamp: timestamp that pusher started to work
log = `${airnodeAddress} - ${stage} - ${pusherVersion} - ${currentTimestamp} - ${deploymentTimestamp} - ${pusherConfigHash} - ${heartbeatSignature}` 
```
This is required because we need to make sure
* the API provider deployed the correct thing
* pusher is alive

and also we need to keep track of deployments in [api-integrations](https://github.com/api3dao/api-integrations).

This is blocked by https://github.com/api3dao/signed-api/issues/95 because it requires `stage` and `pusherVersion`.

**Comment by Siegrift** [comment]
For `deploymentTimestamp` is enough to take a timestamp when the pusher is started ([here](https://github.com/api3dao/signed-api/blob/fb5be4ebf8b6c405a948cc58b697b3a115e50111/packages/pusher/src/index.ts#L6C1-L6C1))?

**Comment by metobom** [comment]
Yes, it is enough.
